### ISSUE TITLE
Provide feedback on my.opencures.org

### ISSUE THREAD

**Issue by vincenzodomina** [curedao/curedao-monorepo#30]
Phase 1 until April 1st

General User stories for testing:

- Registration/ Account handling process: Signup, Logout, Relogin, Delete account, change/reset Password, check related emails and flows
- Profile setup: Fill questionnaire and user profile, change, delete, double check entry against representation
- User data: Upload data, view data, check values and units. (PDF)
Life extension:
https://www.lifeextension.com/lab-testing/itemlc322582/male-panel-blood-test
Labcorb:
https://files.labcorp.com/testmenu-d8/sample_reports/322000.pdf
- General user experience: Do you find it intuitive, do you find what you need, etc ?
     e.g. loading times
- Navigation: is every link and page direction working?

Functional stories:
- As as user i want to aggregate / upload my data and make sense of it. It should be correct data.
- As a User I want to export my data for my personal backup purposes
- As a User I want to chart my data (timelines, correlations) to find insights

**Comment by mikepsinn** [comment]
I think this is done.
