### ISSUE TITLE
Removing "Save Password" when trying to add a measurement

### ISSUE THREAD

**Issue by AMelhede** [curedao/curedao-monorepo#36]
When trying to add a new measurement, the "Save Password" section regularly pops up:
![image](https://user-images.githubusercontent.com/95473109/226518558-328444e1-4e03-4178-bb45-683febc4bfdd.png)

**Comment by mikepsinn** [comment]
I don't think this is a result of a bug in the app. Maybe a browser issue. That has never happened to me.  

Did you log in with email/password?  

Did you click "Save" or "No Thanks"?  After you click one of those, it should go away?  Or did you click one, and it still keeps coming back?

**Comment by AMelhede** [comment]
Initially, I just closed it without clicking either "Save" or "No Thanks."
Now, I just pressed "Save" and refreshed the page.
It seems to be gone now, @mikepsinn.
