### ISSUE TITLE
The measurement keeps on showing the previously inputted option

### ISSUE THREAD

**Issue by AMelhede** [curedao/curedao-monorepo#37]
After adding cacao powder as a measurement, I wanted to add a water measurement as well, but every time I try to add the water measurement, it keeps on showing me the previous cacao powder measurement as seen below:

![image](https://user-images.githubusercontent.com/95473109/226518612-5cefb5e0-4ad2-48a5-935b-2cb24205ada7.png)

![image](https://user-images.githubusercontent.com/95473109/226518589-e4a50691-193e-4907-a85a-c82f8982c635.png)

The same happened when trying to input other measurements such as Himalayan salt after inputting an espresso:

![image](https://user-images.githubusercontent.com/95473109/226524638-fc089bc0-f4f4-4687-8f25-d7156cf0d8b8.png)

![image](https://user-images.githubusercontent.com/95473109/226524548-6007d76c-3e03-4542-a449-943823a6455f.png)

I notice it happens when you want to record two or more measurements after another.
You have to go to another page for you to be able to record the new measurement properly.

**Comment by AMelhede** [comment]
The same happened when trying to input Himalayan salt after inputting an espresso:

![image](https://user-images.githubusercontent.com/95473109/226524638-fc089bc0-f4f4-4687-8f25-d7156cf0d8b8.png)


![image](https://user-images.githubusercontent.com/95473109/226524548-6007d76c-3e03-4542-a449-943823a6455f.png)

**Comment by mikepsinn** [comment]
@AMelhede Thanks for pointing this out! I got it fixed!
